destinationCluster:
  kafkaRestClass: krc-example

sourceCluster:
  boostrapEndpoint: example.com:9092
  clusterId: test_kafka_cluster_id

consumerGroupFilters:
  - name: filter-example
    patternType: LITERAL
    filterType: INCLUDE

configs:
  connections.max.idle.ms: "620000"
  cluster.link.retry.timeout.ms: "320000"

mirrorTopics:
  - name: testTopic
  - name: demo
    replicationFactor: 3
    sourceTopicName: demo
    state: "ACTIVE"