apiVersion: platform.confluent.io/v1beta1
kind: ClusterLink
metadata:
  name: {{ include "clusterlink.fullname" . }}
  labels:
    {{- include "clusterlink.labels" . | nindent 4 }}
spec:
  {{- toYaml .Values.spec | nindent 2 }}