apiVersion: platform.confluent.io/v1beta1
kind: ClusterLink
metadata:
  name: {{ include "clusterlink.fullname" . }}
  labels:
    {{- include "clusterlink.labels" . | nindent 4 }}
spec:
  destinationKafkaCluster:
    kafkaRestClassRef:
      name: {{ .Values.destinationCluster.kafkaRestClass.name }}
  sourceKafkaCluster:
    bootstrapEndpoint: {{ .Values.sourceCluster.boostrapEndpoint }}
    clusterID: {{ .Values.sourceCluster.clusterId }}
  {{ if .Values.consumerGroupFilters -}}
  consumerGroupFilters:
    {{- toYaml .Values.consumerGroupFilters | nindent 4 }}
  {{- end }}
  {{ if .Values.aclFilters -}}
  aclFilters:
    {{- toYaml .Values.aclFilters | nindent 4 }}
  {{- end }}
  {{ if .Values.mirrorTopics -}}
  mirrorTopics:
    {{- toYaml .Values.mirrorTopics | nindent 4 }}
  {{- end -}}
  {{- if .Values.configs -}}
  configs:
    {{- include "clusterlink.configs" . | nindent 4 }}
  {{- end }}