apiVersion: platform.confluent.io/v1beta1
kind: ClusterLink
metadata:
  name: {{ include "clusterlink.fullname" . }}
  labels:
    {{- include "clusterlink.labels" . | nindent 4 }}
spec:
  destinationKafkaCluster:
    {{- if .Values.destinationCluster.bootstrapEndpoint }}
    bootstrapEndpoint: "{{ .Values.destinationCluster.bootstrapEndpoint }}"
    {{- end }}
    {{- if .Values.destinationCluster.clusterID }}
    clusterID: "{{ .Values.destinationCluster.clusterID }}"
    {{- end }}
    {{- if .Values.destinationCluster.kafkaRestClass }}
    kafkaRestClassRef:
      name: {{ .Values.destinationCluster.kafkaRestClass.name }}
      {{- if .Values.destinationCluster.kafkaRestClass.namespace }}
      namespace: {{ .Values.destinationCluster.kafkaRestClass.namespace }}
      {{- end }}
    {{- end }}
    {{- if .Values.destinationCluster.authentication }}
    authentication:
      {{- toYaml .Values.destinationCluster.authentication | nindent 6 }}
    {{- end }}
    {{- if .Values.destinationCluster.tls }}
    tls:
      {{- toYaml .Values.destinationCluster.tls | nindent 6 }}
    {{- end }}
  sourceKafkaCluster:
    {{- if .Values.sourceCluster.bootstrapEndpoint }}
    bootstrapEndpoint: "{{ .Values.sourceCluster.bootstrapEndpoint }}"
    {{- end }}
    {{- if .Values.sourceCluster.clusterID }}
    clusterID: "{{ .Values.sourceCluster.clusterID }}"
    {{- end }}
    {{- if .Values.sourceCluster.kafkaRestClass }}
    kafkaRestClassRef:
      name: {{ .Values.sourceCluster.kafkaRestClass.name }}
      {{- if .Values.sourceCluster.kafkaRestClass.namespace }}
      namespace: {{ .Values.sourceCluster.kafkaRestClass.namespace }}
      {{- end }}
    {{- end }}
    {{- if .Values.sourceCluster.authentication }}
    authentication:
      {{- toYaml .Values.sourceCluster.authentication | nindent 6 }}
    {{- end }}
    {{- if .Values.sourceCluster.tls }}
    tls:
      {{- toYaml .Values.sourceCluster.tls | nindent 6 }}
    {{- end }}
  {{ if .Values.consumerGroupFilters -}}
  consumerGroupFilters:
    {{- toYaml .Values.consumerGroupFilters | nindent 4 }}
  {{- end }}
  {{ if .Values.aclFilters -}}
  aclFilters:
    {{- toYaml .Values.aclFilters | nindent 4 }}
  {{- end }}
  {{ if .Values.mirrorTopics -}}
  mirrorTopics:
    {{- toYaml .Values.mirrorTopics | nindent 4 }}
  {{- end -}}
  {{- if .Values.configs }}
  configs:
    {{- include "clusterlink.configs" . | nindent 4 }}
  {{- end }}